apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: clueforge
spec:
  replicas: 1
  template:
    spec:
      initContainers:
        - name: repo-cloner
          image: alpine/git:latest
          securityContext:
            runAsUser: 1001020000
            fsGroup: 1001020000
          command: ['sh', '-c']
          args:
            - |
              cd /opt/app-root/src/workspace
              if [ ! -d "assisted-service" ]; then
                git clone https://github.com/openshift/assisted-service.git assisted-service
                cd assisted-service && git checkout master
              else
                cd assisted-service && git pull origin master
              fi
              echo "Assisted-service cloned/pulled to workspace"
          volumeMounts:
            - name: repo-workspace-volume
              mountPath: /opt/app-root/src/workspace
      containers:
        - image: quay.io/rhads-jowilkin/clueforge:2f56f161179fe270f71ad5e842df714934f52a47@sha256:0994d503fe4d2efc761d042fb4497ab57a3cf56c40deff97fbbb38f9324255e6
          name: container-image
          volumeMounts:
            - name: repo-workspace-volume
              mountPath: /opt/app-root/src/workspace
      volumes:
        - name: repo-workspace-volume
          persistentVolumeClaim:
            claimName: clueforge-repo-workspace