apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clueforge-repo-workspace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-cephfs